server:
  port: 7070

spring:
  profiles:
    active: debug
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

fileConfig:
  uploadTempBasePath: D:\


